bkmk/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # path('/', views.main, name = 'main'),
    path('signup/', views.signup, name = 'signup'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('delete/', views.delete, name = 'delete'),
    path('update/', views.update, name = 'update'),
    path('<int:user_pk>/', views.detail, name = 'detail'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

bkmk/bkmk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('reviews/', include('reviews.urls')),
]

bkmk/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.main, name='main'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('genre_list/<int:genre_pk>/', views.genre_list, name='genre_list'),
    path('recommend/', views.recommend, name='recommend'),
]

bkmk/reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.reviewlist, name='reviewlist'),
    path('<int:movie_pk>/create/', views.create, name='create'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/like', views.like, name='like'),
]

bkmk/reviews/models.py
from django.db import models
from django.conf import settings
from movies.models import Movie

# Create your models here.

class Review(models.Model):
    POINT_CHOICES = (
        (1, '⭐'),
        (2, '⭐⭐'),
        (3, '⭐⭐⭐'),
        (4, '⭐⭐⭐⭐'),
        (5, '⭐⭐⭐⭐⭐'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='userreview')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    star_point = models.IntegerField(choices=POINT_CHOICES, default=5)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')

bkmk/reviews/forms.py
from django import forms
from .models import Review

class ReviewCreateForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'content', 'star_point']

class ReviewUpdateForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'content']

bkmk/reviews/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.conf import settings
from .models import Review
from .forms import ReviewCreateForm, ReviewUpdateForm
from movies.models import Movie


# Movie = Review.movie
@login_required
def reviewlist(request):
    reviews = Review.objects.all()
    top_reviews = Review.objects.order_by('-like_users')[:3] #인기 top3
    context = {
        'reviews':reviews,
        'top_reviews':top_reviews,
    }
    return render(request, 'reviews/reviewlist.html', context)

@login_required
def create(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.user.is_authenticated:
        if request.method == "POST":
            form = ReviewCreateForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.user = request.user
                review.movie = movie
                review.save()
                return redirect('reviews:detail', review.pk)
        else:
            form = ReviewCreateForm()
        context = {
            'form':form
        }
        return render(request, 'reviews/form.html', context)
    else:
        messages.warning(request, '로그인을 해주세요.')
        return redirect('accounts: login')

@login_required
def update(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user.is_authenticated:
        if request.user == review.user:
            if request.method == "POST":
                form = ReviewUpdateForm(request.POST, instance=review)
                if form.is_valid():
                    updated_review = form.save(commit=False)
                    updated_review.user = request.user
                    updated_review.save()
                    return redirect('reviews:detail', review.pk)
            else:
                form = ReviewUpdateForm(instance=review)
            context = {
                'form':form
            }
            return render(request, 'reviews/form.html', context)
        else:
            messages.warning(request, '본인 글만 수정 가능합니다.')
            return redirect('reviews:detail', review.pk)
    else:
        messages.warning(request, '로그인을 해주세요')
        return redirect('accounts:login')



def delete(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user.is_authenticated:
        if request.user == review.user:
            review.delete()
            return redirect('reviews:reviewlist')
        else:
            messages.warning(request, '본인 글만 수정 가능합니다.')
            return redirect('reviews:detail', review.pk)
    else:
        messages.warning(request, '로그인을 해주세요')
        return redirect('accounts:login')

def detail(request, review_pk):
    review = get_object_or_404(Review, pk = review_pk)
    movie = review.movie
    context = {
        'movie': movie,
        'review': review,
    }
    return render(request, 'reviews/detail.html', context)

@login_required
def like(request, review_pk):
    review = get_object_or_404(Review, pk = review_pk)
    # if request.user != review.user:
    if review.like_users.filter(id=request.user.pk).exists():
        review.like_users.remove(request.user)
    else:
        review.like_users.add(request.user)
    return redirect('reviews:detail', review.pk)

bkmk/reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
    {{ review.user.username }}님의 리뷰
{% endblock %}
{% block content %}

<head>
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
  />
</head>

<div class='review_cre'>
    <div class="columns is-centered" style="margin-top: 2rem; margin-bottom: 5rem;" id="reviews">
        <div class="column reviews" style="max-width: 650px; padding: 0;">
            <h2> <a class="text-dark" href="{% url 'movies:detail' review.movie.pk %}">[{{ review.movie.title }}🎥]</a> {{ review.title }}</h2>
            <p><a class="text-dark" href="{% url 'accounts:detail' review.user.pk %}">{{ review.user.username }}님</a></p>
            <p class="text-secondary">{{ review.created_at }} | 수정: {{ review.updated_at }}</p>
            <p>{{ review.content }}</p>
            {% if review.user == request.user  %}
            <div class="text-right">
                <a href="{% url 'reviews:update' review.pk %}"><button class="btnSubmit btn-secondary">수정</button></a>
                <form action="{% url 'reviews:delete' review.pk %}" method="POST" class="d-inline">
                    {% csrf_token %}
                    <button class="btnSubmit btn-secondary">삭제</button>
                </form>
            </div>
            <hr>
            {% endif %}
            {% with review_like_users=review.like_users.all %}
                {% if request.user in review_like_users %}
                    <a href="{% url 'reviews:like' review.pk %}">
                        <i class="fas fa-heart fa-lg animated delay-1s" style="color: red;"></i>
                    </a>
                {% else %}
                    <a href="{% url 'reviews:like' review.pk %}">
                        <i class="far fa-heart fa-lg animated infinite bounce delay-1s" style="color: gray;"></i>
                    </a>
                {% endif %}
                <p>{{ review_like_users|length }}명이 좋아합니다.</p>
            {% endwith %}
        </div>
    </div>
</div>
{% endblock %}

{% block style %}
<style>
@import url(//fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet");
.btnSubmit{
    font-weight: 500;
    width: 20%;
    color: #282726;
    background-color: #F08080;
    border: none;
    border-radius: 1.5rem;
    padding:1.3%;
    font-family: 'Jua', sans-serif;
    width: 47%;
}
.review_cre{
    font-family: 'Jua', sans-serif;
}
</style>

{% endblock %}

bkmk/reviews/templates/reviews/form.html
{% extends 'base.html' %}

{% block title %}
        {% if request.resolver_match.url_name == 'create' %}
            리뷰 작성
        {% else %}
            리뷰 수정
        {% endif %}
{% endblock %}
{% load bootstrap4 %}
{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btnSubmit">제출</button>
    </form>
    <hr>
{% endblock %}

{% block style %}

<style>
@import url(//fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet");
.btnSubmit{
    font-weight: 600;
    width: 10%;
    color: #282726;
    background-color: #F08080;
    border: none;
    border-radius: 1.5rem;
    padding:1%;
    font-family: 'Jua', sans-serif;
}
.review_cre{
    font-family: 'Jua', sans-serif;
}
</style>

{% endblock %}

bkmk/reviews/templates/reviews/reviewlist.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
    리뷰 목록
{% endblock %}
{% block content %}
<br>
<div class="container bg-light">
  <br>
  <h2 class="title">리뷰 Top 3📝</h2>
  <br>
  <div class="card-group">
    {% for top_review in top_reviews %}
    <div class="card">
      <div class="card-body">
        <a class="text-dark" href="{% url 'reviews:detail' top_review.pk %}"><h5 class="card-title">[{{ top_review.movie.title }}]{{ top_review.title }}</h5></a>
        <p class="card-text">{{ top_review.content|slice:':20' }}...</p>
        <a href="{% url 'accounts:detail' top_review.user.pk %}"><p class="card-text"><small class="text-muted font-weight-bold">{{ top_review.user.username }}</small></p></a>
        <p class="card-text"><small class="text-muted">{{ top_review.created_at }}</small></p>
      </div>
    </div>
    {% endfor %}
  </div>
  <br>
</div>
<hr>
<h2 class="title">리뷰 목록</h2>
<div class="list-group">
  {% for review in reviews %}
  <!--<a href="#" class="list-group-item list-group-item-action active">-->
  <a href="{% url 'reviews:detail' review.pk %}" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">[{{ review.movie.title }}] {{ review.title }}</h5>
      <small class="text-muted">{{ review.created_at}}</small>
    </div>
    <p class="mb-1">{{ review.content|slice:':15' }}...</p>
    <small class="text-muted">{{ review.user }}</small>
  </a>
  {% endfor %}
{% endblock %}

{% block style %}

<style>
@import url(//fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet");
.list-group{
  font-family: 'Jua', sans-serif;
}
.card{
  font-family: 'Jua', sans-serif;
}
.title{
  font-family: 'Jua', sans-serif;
}
</style>

{% endblock %}