bkmk/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # path('/', views.main, name = 'main'),
    path('signup/', views.signup, name = 'signup'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('delete/', views.delete, name = 'delete'),
    path('update/', views.update, name = 'update'),
    path('<int:user_pk>/', views.detail, name = 'detail'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

bkmk/bkmk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('reviews/', include('reviews.urls')),
]

bkmk/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.main, name='main'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('genre_list/<int:genre_pk>/', views.genre_list, name='genre_list'),
    path('recommend/', views.recommend, name='recommend'),
]

bkmk/reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.reviewlist, name='reviewlist'),
    path('<int:movie_pk>/create/', views.create, name='create'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/like', views.like, name='like'),
]

bkmk/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}
    {% endblock %}
    <!--bootstrap css-->
    <link href="https://fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block style %}{% endblock %}
</head>
<body>
    <!--axios-->
    <!--<script src="https://unpkg.com/axios/dist/axios.min.js"></script>-->
    <!--bootstrap js-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% include 'navbar.html' %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% block script %}{% endblock %}
</body>
</html>

bkmk/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand text " href="{% url 'movies:main' %}">볼까말까 BKMK 👀</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
          <li class="nav-item align-self-center">
            <a class="nav-link active" href="{% url 'movies:recommend' %}">맞춤 영화 추천👍🏻 </a>
          </li>
          <li class="nav-item align-self-center">
            <a class="nav-link" href="{% url 'movies:main' %}">영화목록</a>
          </li>
          <li class="nav-item align-self-center">
            <a class="nav-link" href="{% url 'reviews:reviewlist' %}">리뷰목록</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <!--프로필이미지 삽입-->
              {{ user.username }}님, 환영합니다.
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'accounts:detail' user.pk %}">마이페이지</a>
              <a class="dropdown-item" href="{% url 'accounts:update' %}">나의 정보수정</a>
              <a class="dropdown-item" href="{% url 'accounts:logout' %}">로그아웃</a>
              <a class="dropdown-item" href="{% url 'accounts:delete' %}">회원 탈퇴</a>
            </div>
          </li>
      {% endif %}
    </ul>
  </div>
</nav>

{% block style %}

<style>
@import url(//fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet");

.nav-link{
    font-family: 'Jua', sans-serif;
}
.dropdown-item{
    font-family: 'Jua', sans-serif;
}
.navbar-brand{
    font-family: 'Jua', sans-serif;
}
</style>

{% endblock %}