bkmk/bkmk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('reviews/', include('reviews.urls')),
]

bkmk/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.main, name='main'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('genre_list/<int:genre_pk>/', views.genre_list, name='genre_list'),
    path('recommend/', views.recommend, name='recommend'),
]

bkmk/reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.reviewlist, name='reviewlist'),
    path('<int:movie_pk>/create/', views.create, name='create'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/like', views.like, name='like'),
]

bkmk/movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=100)
    original_title = models.CharField(max_length=100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    adult = models.BooleanField()
    overview = models.TextField()
    original_language = models.CharField(max_length=100)
    poster_path = models.CharField(max_length=200)
    backdrop_path = models.CharField(max_length=200)
    genres = models.ManyToManyField(Genre, related_name='movies')

    # director = models.CharField(max_length=100, default="")
    # runtime = models.CharField(max_length=50, default="")
    # production_company = models.CharField(max_length=50, default="")

    def __str__(self):
        return self.title

bkmk/movies/forms.py
from django import forms
# from .models import Genre

# class GenreForm(forms.ModelForm):
#     class Meta:
#         model = Genre


# from django import forms
# from .models import Genre

# USER_GENRE_CHOICES = (
#     ('28', '액션'), ('16', '애니메이션'), ('99', '다큐멘터리'),
#     ('18', '드라마'), ('10751', '가족'), ('14', '판타지'),
#     ('36', '역사'), ('35', '코메디'), ('10752', '전쟁'),
#     ('80', '범죄'), ('10402', '음악'), ('9648', '미스터리'),
#     ('10749', '로맨스'), ('878', 'SF'), ('27', '호러'),
#     ('10770', 'TV영화'), ('53', '스릴러'), ('37', '서부'),
#     ('12', '모험'),
# )

# class GenreForm(forms.ModelForm):
#     name = forms.MultipleChoiceField(label='', required=False, widget=forms.CheckboxSelectMultiple(), choices=GENRE_CHOICES,)
#     class Meta:
#         model = Genre
#         fields = ['name']

bkmk/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Genre, Movie
from reviews.models import Review
# from .forms import GenreForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.db.models import Q
from .serializers import MovieSerializer
from rest_framework.response import Response
from rest_framework.decorators import api_view
import random

# Create your views here.


MY_API_KEY = '3216cd88663607c5472c0d1e54a7193a' # 환경변수로 만들어야 함

@login_required
def main(request):
    user = request.user
    usergenre = user.usergenre
    usergenre_list = list(usergenre[1:-1].split(', '))

    order = "Movie.objects.filter("
    for genre_id in usergenre_list:
        ID = genre_id[1:-1]
        order += f"Q(genres=int({ID}))|"
    order = order[:-1] + ')'
    if order == 'Movie.objects.filter(':
        raise Exception
    num = random.randint(1, 20)
    recommend_movie = eval(order+'[num-1:num]')
    r_reviews = Review.objects.filter(movie=recommend_movie)
    count=numsum=0
    for review in r_reviews:
        numsum += review.star_point
        count+=1
    average = 0
    if count:
        average = int(numsum/count)
    average_point=[]
    for i in range(average):
        average_point.append(i)

    movies = Movie.objects.all()
    paginator = Paginator(movies, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'user':user,
        'movies': movies,
        'page_obj': page_obj,
        'recommend_movie':recommend_movie[0],
        'average_point':average_point,
    }
    return render(request, 'movies/main.html', context)

@login_required
def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    reviews = Review.objects.filter(movie_id=movie.pk)
    popularity = int(movie.popularity)

    r_reviews = Review.objects.filter(movie=movie)
    count=numsum=0
    for review in r_reviews:
        numsum += review.star_point
        count+=1
    average = 0
    if count:
        average = int(numsum/count)
    average_point=[]
    for i in range(average):
        average_point.append(i)

    context = {
        'movie': movie,
        'popularity':popularity,
        'reviews':reviews,
        'average_point':average_point,
    }
    return render(request, 'movies/detail.html', context)

@login_required
def genre_list(request, genre_pk):
    genre_choice = get_object_or_404(Genre, pk=genre_pk)
    movies = Movie.objects.filter(genres=genre_choice.pk).order_by('-vote_average')
    genres = Genre.objects.all()
    paginator = Paginator(movies, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'genre_choice':genre_choice,
        'movies':movies,
        'page_obj':page_obj,
    }
    return render(request, 'movies/genre_list.html', context)

@login_required
def recommend(request):
    user = request.user
    usergenre = user.usergenre
    usergenre_list = list(usergenre[1:-1].split(', '))

    order = "Movie.objects.filter("
    for genre_id in usergenre_list:
        ID = genre_id[1:-1]
        order += f"Q(genres=int({ID}))|"
    order = order[:-1] + ')'
    if order == 'Movie.objects.filter(':
        raise Exception
    recommend_movies = eval(order+".order_by('-vote_average')")
    paginator = Paginator(recommend_movies, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'user':user,
        'recommend_movies': recommend_movies,
        'page_obj': page_obj,
    }
    return render(request, 'movies/recommend.html', context)

bkmk/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block title %}
    {{ movie.title }}
{% endblock %}
<!--<img src='{% static "images/yellow-bokeh.jpg" %}'id="bg" alt="">-->
<!--<div background='{% static "images/yellow-bokeh.jpg" %}'>-->
{% block content %}
<!--<span class="badge badge-secondary">{{ popularity }}point!</span></h2>-->

<br>
<div class="container gen-container">
    <div class="row">
        <div class="col-md ml-auto mr-auto">
            <h2>{{ movie.title }}</h2>
            <img src="https://image.tmdb.org/t/p/w342{{ movie.poster_path }}" alt="{{ movie.title }}의 poster">
        </div>
        <div class="col-md mt-auto ml-5 mb-5">
            <h5>개봉일 : {{ movie.release_date }}</h5>
            {% if average_point %}
                <h5>평점 :
                    {% for i in average_point %}
                        ⭐
                    {% endfor %}
                </h5>
            {% else %}
                <h5>아직 평점이 없습니다! 리뷰를 남겨보세요.</h5>
            {% endif %}
            <h5>장르 :
                {% for genre in movie.genres.all %}
                <a href="{% url 'movies:genre_list' genre.pk %}"><span class="badge">{{ genre.name }}</span></a>
                {% endfor %}
            </h5>
            <p>{{ movie.overview }}</p>
            <a href="{% url 'reviews:create' movie.pk %}" class="btnSubmit text-dark">리뷰 남기러 가기</a>
        </div>
    </div>
</div>
    <hr>
    <table class="table">
      <tbody>
        {% for review in reviews %}
            <tr>
                <th scope="row"></th>
                <td></td>
                <td><a class="text-dark" href="{% url 'reviews:detail' review.pk %}">{{ review.title }}</a></td>
                <td>{{ review.user.username }}</td>
                <td>{{ review.created_at }}</td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}

{% block style %}

<style>
@import url(//fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet");

.gen-container{
    font-family: 'Jua', sans-serif;
}
.h2{
    font-family: 'Jua', sans-serif;
}
.badge{
    font-family: 'Jua', sans-serif;
    font-weight: 600;
    color: white;
    background-color: black;
    border: none;
    border-radius: 1.5rem;
    padding:1.3%;
    cursor: pointer;
}
.btnSubmit{
    font-weight: 600;
    width: 10%;
    color: #282726;
    background-color: #F08080;
    border: none;
    border-radius: 1.5rem;
    padding:2%;
    font-family: 'Jua', sans-serif;
}
.table{
    font-family: 'Jua', sans-serif;
}
</style>

{% endblock %}

bkmk/movies/templates/movies/genre_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load bootstrap_pagination %}

{% block title %}
    {{ user.username }}님의 맞춤 영화
{% endblock %}
{% block content %}
    <br>
    <div class="movie_list">
    <h1>{{ user.username }}님, 이런 영화는 어떠신가요?</h1>
    <br>
    </div>
    <div class="container movie-container" style="display: inline-block;text-align: center;">
        <div class="row justify-content-between">
            {% for movie in page_obj %}
                <div class="col d-flex mb-3">
                    <div class="card" style="width: 18rem;">
                      <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" class="card-img-top" alt="...">
                      <div class="card-body">
                        <h5 class="card-title">{{ movie.title }}</h5>
                        <p class="card-text">{{ movie.overview|slice:':20' }}...</p>
                        <a href="{% url 'movies:detail' movie.pk %}" class="btnSubmit">더 알아보기</a>
                      </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
    {% bootstrap_paginate page_obj range=10 show_prev_next="true" show_first_last="true" %}
{% endblock %}

{% block script %}
<div class='pagination'>
    <script>
        // paginator
        const paginator = document.querySelector('.pagination');
        paginator.classList.add('justify-content-center', 'my-5');
    </script>
</div>
{% endblock %}

{% block style %}
<style>
@import url(//fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet");
.btnSubmit{
    font-family: 'Jua', sans-serif;
    font-weight: 600;
    width: 50%;
    color: black;
    background-color: #F08080;
    border: none;
    border-radius: 1.5rem;
    padding:2%;
    cursor: pointer;
}
.btnSubmit:hover {
    color: black;
    background-color: #F08080;
}
.movie_list{
    font-family: 'Jua', sans-serif;
}
.movie-container{
    font-family: 'Jua', sans-serif;
}
</style>

{% endblock %}

bkmk/movies/templates/movies/main.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load bootstrap_pagination %}


{% block title %}
영화, 볼까말까?
{% endblock %}
{% block content %}
<div class="recommend_list">
  <div class="card-body">
    <div class="card" style="width: 100%;">
      <h5 class="card-title ml-3 mt-3">{{ user.username }}님, 이런 영화는 어떠신가요?🍿</h5>
      <div class="container mt-1 mb-3" style="width: 80%;">
          <div class="row">
              <div class="col">
                  <img src="https://image.tmdb.org/t/p/w500/{{ recommend_movie.poster_path }}" style="width: 18rem;" alt="{{ movie.title }}">
              </div>
              <div class="col mb-3">
                <a class="text-dark" href="{% url 'movies:detail' recommend_movie.pk %}"><h4>{{ recommend_movie.title }}</h4></a>
                <h5>개봉일 : {{ recommend_movie.release_date }}</h5>
                {% if average_point %}
                <h5>평점 :
                    {% for i in average_point %}
                        ⭐
                    {% endfor %}
                </h5>
                {% else %}
                <h5>아직 평점이 없습니다! 리뷰를 남겨보세요.</h5>
                {% endif %}
                <h5>장르 :
                    {% for genre in recommend_movie.genres.all %}
                    <a href="{% url 'movies:genre_list' genre.pk %}"><span class="badge badge-dark">{{ genre.name }}</span></a>
                    {% endfor %}
                </h5>
                <p class="card-text">{{ recommend_movie.overview|slice:':500' }}...</p>
                <br>
                <a href="{% url 'reviews:create' recommend_movie.pk %}" class="btnSubmit text-dark">리뷰 남기러 가기</a>
              </div>
          </div>
      </div>
    </div>
  </div>
</div>
    <!--여기 위에 추천영화-->
    <div class="jumbotron vertical-center">
        <div class="container" style="display: inline-block;text-align: center;">
            <div class="row justify-content-between">
                {% for movie in page_obj %}
                <div class="col d-flex mb-3">
                    <div class="card" style="width: 18rem;">
                      <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" class="card-img-top" alt="...">
                      <div class="card-body">
                        <h5 class="card-title">{{ movie.title }}</h5>
                        <p class="card-text">{{ movie.overview|slice:':20' }}...</p>
                        <a href="{% url 'movies:detail' movie.pk %}" class="btnSubmit btn-dark">더 알아보기</a>
                      </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% bootstrap_paginate page_obj range=10 show_prev_next="true" show_first_last="true" %}
{% endblock %}

{% block script %}
<div class='pagination'>
    <script>
        // paginator
        const paginator = document.querySelector('.pagination');
        paginator.classList.add('justify-content-center', 'my-5');
    </script>
</div>
{% endblock %}

{% block style %}

<style>
@import url(//fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet");

.btn{
    font-weight: 600;
    width: 50%;
    color: black;
    background-color: #F08080;
    border: none;
    border-radius: 1.5rem;
    padding:1.3%;
    font-family: 'Jua', sans-serif;
}
.badge{
    padding:1.3%;
}
.card-body{
    font-family: 'Jua', sans-serif;
    font-weight: 580;
}
.recommend_list{
    font-family: 'Jua', sans-serif;
}

.btnSubmit{
    font-family: 'Jua', sans-serif;
    font-weight: 600;
    width: 50%;
    color: black;
    background-color: #F08080;
    border: none;
    border-radius: 1.5rem;
    padding:2%;
    cursor: pointer;
}
</style>

{% endblock %}

bkmk/movies/templates/movies/recommend.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load bootstrap_pagination %}

{% block title %}
    {{ user.username }}님의 맞춤 영화
{% endblock %}
{% block content %}
    <br>
    <div class="movie_list">
    <h2>{{ user.username }}님에게 추천하는 영화🎥</h2>
    <br>
    </div>
    <div class="container" style="display: inline-block;text-align: center;">
        <div class="row justify-content-between">
            {% for movie in page_obj %}
                <div class="col d-flex mb-3">
                    <div class="card" style="width: 18rem;">
                      <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" class="card-img-top" alt="...">
                      <div class="card-body">
                        <h5 class="card-title">{{ movie.title }}</h5>
                        <p class="card-text">{{ movie.overview|slice:':20' }}...</p>
                        <a href="{% url 'movies:detail' movie.pk %}" class="btnSubmit">더 알아보기</a>
                      </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
    {% bootstrap_paginate page_obj range=10 show_prev_next="true" show_first_last="true" %}
{% endblock %}
{% block script %}
<div class='pagination'>
    <script>
        // paginator
        const paginator = document.querySelector('.pagination');
        paginator.classList.add('justify-content-center', 'my-5');
    </script>
</div>
{% endblock %}
{% block style %}

<style>
@import url(//fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet");
.btnSubmit{
    font-family: 'Jua', sans-serif;
    font-weight: 600;
    width: 50%;
    color: black;
    background-color: #fff;
    border: none;
    border-radius: 1.5rem;
    padding:2%;
    cursor: pointer;
}
.btnSubmit:hover {
    color: white;
    background-color: black;
}
.movie_list{
    font-family: 'Jua', sans-serif;
}
</style>

{% endblock %}