bkmk/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # path('/', views.main, name = 'main'),
    path('signup/', views.signup, name = 'signup'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('delete/', views.delete, name = 'delete'),
    path('update/', views.update, name = 'update'),
    path('<int:user_pk>/', views.detail, name = 'detail'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

bkmk/bkmk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('reviews/', include('reviews.urls')),
]

bkmk/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class User(AbstractUser):
    ADULT_CHOICES = (
        (True, 'YES'),
        (False, 'NO'),
    )

    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings', blank=True)
    age = models.IntegerField(validators=[MinValueValidator(13), MaxValueValidator(100)], default=13)
    usergenre = models.CharField(max_length=500, default='1')
    use_adult = models.BooleanField(choices=ADULT_CHOICES, default=False)

bkmk/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django import forms

USER_GENRE_CHOICES = (
    (28, '액션'),
    (16, '애니메이션'),
    (99, '다큐멘터리'),
    (18, '드라마'),
    (10751, '가족'),
    (14, '판타지'),
    (36, '역사'),
    (35, '코메디'),
    (10752, '전쟁'),
    (80, '범죄'),
    (10402, '음악'),
    (9648, '미스터리'),
    (10749, '로맨스'),
    (878, 'SF'),
    (27, '호러'),
    (10770, 'TV영화'),
    (53, '스릴러'),
    (37, '서부'),
    (12, '모험'),
)

class CustomUserChangeForm(UserChangeForm):
    usergenre = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=USER_GENRE_CHOICES)
    class Meta:
        model = get_user_model()
        exclude = ['password']
        fields = ['username', 'email', 'age', 'use_adult', 'usergenre']

class CustomUserCreationForm(UserCreationForm):
    usergenre = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=USER_GENRE_CHOICES)
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'age', 'use_adult', 'usergenre']

bkmk/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages
from reviews.models import Review

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:main')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:main')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/form.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:main')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:main')
    else:
        form = AuthenticationForm()
    context = {
        'form':form,
    }
    return render(request, 'accounts/form.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

@login_required
def delete(request):
    request.user.delete()
    return redirect('movies:main')

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:main')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

def detail(request, user_pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=user_pk)
    reviews = ''
    if Review.objects.filter(user=user):
        reviews = Review.objects.filter(user=user).order_by('-created_at')
    context = {
        'user': user,
        'reviews': reviews,
    }
    return render(request, 'accounts/detail.html', context)

def follow(request, user_pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=user_pk)
    if user != request.user:
        if user.followers.filter(pk=request.user.pk).exists():
            # 삭제
            user.followers.remove(request.user)
        else:
            # 추가
            user.followers.add(request.user)
        return redirect('accounts:detail', user.pk)
    else:
        messages.warning(request, '본인을 팔로우 할 수 없습니다.')
        return redirect('accounts:detail', user.pk)

bkmk/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
      {{ user.username }}님의 페이지
{% endblock %}
{% block content %}
<br>
<div class="jumbotron">
    <div class="container login-container">
        <div class="row">
            <div class="col">
                <div class="sonar-wrapper">
    	        <div class="sonar-emitter">
                <div class="sonar-wave"></div>
                  </div>
                </div>
            </div>
            <div class="col">
            <h5 class="display-5">{{ user.username }}</h5>
            <p class="lead">팔로워: {{ user.followers.count }}</p>
            <p class="lead">팔로잉: {{ user.followings.count }}</p>
            <p class="lead">게시글 작성 갯수: {{ user.userreview.count }}</p>
            {% with user_followers=user.followers.all %}
            {% if request.user in user_followers %}
                <a class="btnSubmit btn-secondary btn-lg" href="{% url 'accounts:follow' user.pk %}" role="button">팔로우 취소</a>
            {% else %}
                <a class="btnSubmit btn-primary btn-lg" href="{% url 'accounts:follow' user.pk %}" role="button">팔로우</a>
            {% endif %}
            {% endwith %}
            </div>
        </div>
    </div>
  <hr class="my-4">
  <ul class="list-group list-group-flush">
      {% if user.userreview.count %}
          {% for review in user.userreview.all %}
          <li class="reviews list-group-item">
            <p>{{ review.movie }}</p>
            <p>{{ review.title }}</p>
            <p>{{ review.created_at }}</p>
          </li>
          {% endfor %}
      {% else %}
          <h4 class="text-black-50 text-center">아직 작성한 리뷰가 없습니다.</h4>
      {% endif %}
  </ul>
{% endblock %}

{% block style %}

<style>
@import url(//fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet");

.login-container{
  font-family: 'Jua', sans-serif;
}
.reviews{
  font-family: 'Jua', sans-serif;
}
.text-center{
    font-family: 'Jua', sans-serif;
}
.display-5{
    font-family: 'Jua', sans-serif;
    border: none;
}
.lead{
    font-family: 'Jua', sans-serif;
}
.btnSubmit{
    font-family: 'Jua', sans-serif;
    font-weight: 600;
    width: 50%;
    color: black;
    background-color: #F08080;
    border: none;
    border-radius: 1.5rem;
    padding:2%;
    cursor: pointer;
}

.btnSubmit:hover {
    color: white;
    background-color: black;
}
html {
  background-color: #cef;
}
html, body, .sonar-wrapper {
  height: 100%;
}

/* Prevent scrollbars to appear when waves go out of bound */
.sonar-wrapper {
  position: relative;
  z-index: 0;
  overflow: hidden;
  padding: 8rem 0;
}

/* The circle */
.sonar-emitter {
  position: relative;
  margin: 0 auto;
  width: 100px;
  height: 100px;
  border-radius: 9999px;
  background-color: HSL(45,100%,50%);
}

/* the 'wave', same shape and size as its parent */
.sonar-wave {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border-radius: 9999px;
  background-color: HSL(45,100%,50%);
  opacity: 0;
  z-index: -1;
  pointer-events: none;
}

/*
  Animate!
  NOTE: add browser prefixes where needed.
*/
.sonar-wave {
  animation: sonarWave 2s linear infinite;
}

@keyframes sonarWave {
  from {
    opacity: 0.4;
  }
  to {
    transform: scale(3);
    opacity: 0;
  }
</style>

{% endblock %}

bkmk/accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}
    {% if request.resolver_match.url_name == 'signup' %}
        회원가입
    {% elif request.resolver_match.url_name == 'login' %}
        로그인
    {% else %}
        회원정보수정
    {% endif %}
{% endblock %}

{% block content %}
    {% if request.resolver_match.url_name == 'login' %}
    <div class="container login-container position-relative">
        <div class="row">
            <div class="col-6 login-form-1" style="background-image: URL(이미지 주소) ;">
                <h1>환영합니다.</h1>
            </div>
            <div class="col-6 login-form-2">
                <h2>아직 회원이 아니신가요?</h2>
                <div style="width: 20rem;">
                    <form action="" method="POST" class="form">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <div>
                        {% buttons %}
                        <div class="container">
                          <div class="row">
                            <div class="col text-center">
                            <button type="submit" class="btnSubmit ">로그인</button>
                                </div>
                            </div>
                        </div>
                        {% endbuttons %}
                        <div class="container">
                          <div class="row">
                            <div class="col text-center">
                            <button type="submit" class="btnSubmit" onclick="location.href='{% url 'accounts:signup' %}'">회원가입</button>
                            </div>
                            </div>
                        </div>
                        </div>
                    </form>

                </div>
            </div>
        	<a href="#" class="intro-banner-vdo-play-btn pinkBg" target="_blank" style="left: 25%;">
            <i class="glyphicon glyphicon-play whiteText" aria-hidden="true"></i>
            <span class="ripple pinkBg"></span>
            <span class="ripple pinkBg"></span>
            <span class="ripple pinkBg"></span>
            </a>
        </div>
    </div>
    {% else %}
        <form action="" method="POST" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btnSubmit">완료</button>
            {% endbuttons %}
        </form>
    {% endif %}
{% endblock %}

{% block style %}

<style>
@import url(//fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet");

.pinkBg {
    background-color: #ed184f!important;
    background-image: linear-gradient(90deg, #fd5581, #fd8b55);
}
.intro-banner-vdo-play-btn{
    height:60px;
    width:60px;
    position:absolute;
    top:50%;
    left:50%;
    text-align:center;
    margin:-30px 0 0 -30px;
    border-radius:100px;
    z-index:1
}
.intro-banner-vdo-play-btn i{
    line-height:56px;
    font-size:30px
}
.intro-banner-vdo-play-btn .ripple{
    position:absolute;
    width:160px;
    height:160px;
    z-index:-1;
    left:50%;
    top:50%;
    opacity:0;
    margin:-80px 0 0 -80px;
    border-radius:100px;
    -webkit-animation:ripple 1.8s infinite;
    animation:ripple 1.8s infinite
}

@-webkit-keyframes ripple{
    0%{
        opacity:1;
        -webkit-transform:scale(0);
        transform:scale(0)
    }
    100%{
        opacity:0;
        -webkit-transform:scale(1);
        transform:scale(1)
    }
}
@keyframes ripple{
    0%{
        opacity:1;
        -webkit-transform:scale(0);
        transform:scale(0)
    }
    100%{
        opacity:0;
        -webkit-transform:scale(1);
        transform:scale(1)
    }
}
.intro-banner-vdo-play-btn .ripple:nth-child(2){
    animation-delay:.3s;
    -webkit-animation-delay:.3s
}
.intro-banner-vdo-play-btn .ripple:nth-child(3){
    animation-delay:.6s;
    -webkit-animation-delay:.6s
}


.login-container{
    margin-top: 5%;
    margin-bottom: 5%;
}
.login-form-1{
    padding: 9%;
    background:#282726;
    box-shadow: 0 5px 8px 0 rgba(0, 0, 0, 0.2), 0 9px 26px 0 rgba(0, 0, 0, 0.19);
}
.login-form-1 h1{
    text-align: center;
    margin-bottom:12%;
    color:#fff;
    font-family: 'Jua', sans-serif;
}
.login-form-2{
    padding: 9%;
    background: #F08080;
    box-shadow: 0 5px 8px 0 rgba(0, 0, 0, 0.2), 0 9px 26px 0 rgba(0, 0, 0, 0.19);
}
.login-form-2 h2{
    text-align: center;
    margin-bottom:12%;
    color: #fff;
    font-family: 'Jua', sans-serif;
}
.login-container form{
    padding: 10%;
}
.btnSubmit{
    font-weight: 600;
    width: 50%;
    color: #282726;
    background-color: #;
    border: none;
    border-radius: 1.5rem;
    padding:2%;
    font-family: 'Jua', sans-serif;
}
</style>

{% endblock %}